spring:
  application:
    name: shinhan-gaecheokja

  datasource:
    url: jdbc:mariadb://localhost:3306/gaecheokja
    username: root
    password: password # Change this to your local database password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
