ALTER TABLE vehicle
    ADD COLUMN latitude DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN longitude DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE';

ALTER TABLE delivery_request
    ADD COLUMN pickup_latitude DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN pickup_longitude DOUBLE NOT NULL DEFAULT 0;
